### ISSUE TITLE
Add `Checker` variant to `match`

### ISSUE THREAD

**Issue by qryxip** [qryxip/snowchains#123]
```yaml
match:
  Checker:
    cmd: cat "$ACTUAL_OUTPUT" | cargo run --bin check-a
    shell: Bash
```

```yaml
match:
  Checker:
    cmd: ~/.cache/online-judge-tools/library-checker-problems/math/sqrt_mod/checker "$INPUT" "$ACTUAL_OUTPUT" "$EXPECTED_OUTPUT"
    shell: Bash
```
